### PR TITLE
Fix rtlsdr_read_async type to match librtlsdr

### PR DESCRIPTION
**Pull request by personjs**
This seems to fix the rtlsdr_cancel_async hanging error on my end

### CODE REVIEW

**Comment by Arkanic** [comment]
Seems to cause abort errors for me
Screenshot 2022-09-22 18 38 57
from this code:
Screenshot 2022-09-22 18 41 28

that arg is the buffer for the readAsync operation, so when it is set to a void it can't be dereferenced properly
if you change "void" to "void *" it works though:
Screenshot 2022-09-22 18 43 42

As for fixing the read async errors it is not so much the closing that is the issue anymore, but more how it causes the program to hang at rtljs.close

Thanks for the pull, will merge when fixed

**Comment by personjs** [comment]
Yeah right after submitting this I realized my test code wasn't actually working. Will continue debugging the async close blocker later today. Also, do you know if it's possible to make `readAsync` a non-blocking function? And shouldn't the data being returned be an array length > 1?

**Comment by Arkanic** [comment]
> Also, do you know if it's possible to make readAsync a non-blocking function? 

It isn't on the most recent update
It was in the past, as it didn't use ffi-napi's `.async` to non-block

> And shouldn't the data being returned be an array length > 1?

Yes. This is the same issue as getBiasTee. I have not been able to figure out how to get arrays in ffi-napi working properly. The only reason `readSync` works is because the array is pre-allocated by ffi-napi before being handed to the readSync function.
This is an issue I am currently working on, but for some reason there isn't much documentation about it

**Comment by Arkanic** [comment]
Basically, at the moment the async part of the library is in an unusable state
The only thing i can thing of is having a separate node.js thread/worker that just uses blocking readSync repeatedly, and have the main thread just pick up an array or whatever from the thread

**Pull request closed without merging**
